# Generated by Django 4.2 on 2023-04-10 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mitarbeiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Mitarbeiter Name')),
                ('telefonma', models.CharField(max_length=20, verbose_name='Mitarbeiter Telefon')),
                ('emailma', models.EmailField(max_length=254, verbose_name='Mitarbeiter Email')),
            ],
        ),
        migrations.CreateModel(
            name='Sprecherinnen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nachname', models.CharField(max_length=30)),
                ('vorname', models.CharField(max_length=30)),
                ('telefon', models.CharField(max_length=30)),
                ('emailadresse', models.EmailField(max_length=254, verbose_name='SMail')),
            ],
        ),
        migrations.CreateModel(
            name='Angebot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=120, verbose_name='Angebot Titel')),
                ('datum', models.DateTimeField(verbose_name='Angebot Datum')),
                ('beschreibung', models.TextField(blank=True)),
                ('apbuchfunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='angebote.mitarbeiter')),
                ('sprecheriAngebot', models.ManyToManyField(blank=True, to='angebote.sprecherinnen')),
            ],
        ),
    ]
