# Generated by Django 4.2 on 2023-04-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angebote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprecherinnen',
            name='emailadresse',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Sprecher:in Mail'),
        ),
        migrations.AlterField(
            model_name='sprecherinnen',
            name='telefon',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
