# Generated by Django 4.2 on 2023-04-11 16:40

from django.db import migrations
import multiselectfield.db.fields
import multiselectfield.validators


class Migration(migrations.Migration):

    dependencies = [
        ('angebote', '0003_sprecherinnen_geburtsdatum'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprecherinnen',
            name='stimmlage',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Hoch', 'Hoch'), ('Mittel', 'Mittel'), ('Tief', 'Tief')], default=None, max_length=16, validators=[multiselectfield.validators.MaxValueMultiFieldValidator(3)]),
        ),
    ]
