# Generated by Django 4.2 on 2023-04-11 16:48

from django.db import migrations
import multiselectfield.db.fields
import multiselectfield.validators


class Migration(migrations.Migration):

    dependencies = [
        ('angebote', '0004_sprecherinnen_stimmlage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprecherinnen',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Sachbuch', 'Sachbuch'), ('Belletristik', 'Belletristik'), ('Krimi/Thriller', 'Krimi/Thriller'), ('Erotik', 'Erotik')], default=None, max_length=43, validators=[multiselectfield.validators.MaxValueMultiFieldValidator(4)]),
        ),
    ]
