# Generated by Django 4.2 on 2023-04-11 17:30

from django.db import migrations
import multiselectfield.db.fields
import multiselectfield.validators


class Migration(migrations.Migration):

    dependencies = [
        ('angebote', '0006_sprecherinnen_charakter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprecherinnen',
            old_name='charakter',
            new_name='stimmcharakter',
        ),
        migrations.AddField(
            model_name='sprecherinnen',
            name='honorarkategorie',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=None, max_length=7, validators=[multiselectfield.validators.MaxValueMultiFieldValidator(1)]),
        ),
    ]
