# Generated by Django 4.2 on 2023-04-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angebote', '0007_rename_charakter_sprecherinnen_stimmcharakter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprecherinnen',
            name='honorarkategorie',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='', max_length=10),
        ),
    ]
