# Generated by Django 4.2 on 2023-04-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angebote', '0009_sprecherinnen_deutsch'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprecherinnen',
            name='englisch',
            field=models.CharField(blank=True, choices=[('keine', 'keine'), ('Vorkenntnisse', 'Vorkenntnisse'), ('Gut', 'Gut'), ('Fliessend', 'Fliessend'), ('Muttersprache', 'Muttersprache')], default='', max_length=13, verbose_name='Englisch (GB)'),
        ),
        migrations.AlterField(
            model_name='sprecherinnen',
            name='deutsch',
            field=models.CharField(blank=True, choices=[('keine', 'keine'), ('Vorkenntnisse', 'Vorkenntnisse'), ('Gut', 'Gut'), ('Fliessend', 'Fliessend'), ('Muttersprache', 'Muttersprache')], default='', max_length=13, verbose_name='Deutsch'),
        ),
    ]
