# Generated by Django 4.2 on 2023-04-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angebote', '0010_sprecherinnen_englisch_alter_sprecherinnen_deutsch'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprecherinnen',
            name='englischus',
            field=models.CharField(blank=True, choices=[('keine', 'keine'), ('Vorkenntnisse', 'Vorkenntnisse'), ('Gut', 'Gut'), ('Fliessend', 'Fliessend'), ('Muttersprache', 'Muttersprache')], default='', max_length=13, verbose_name='Englisch (US)'),
        ),
        migrations.AddField(
            model_name='sprecherinnen',
            name='französisch',
            field=models.CharField(blank=True, choices=[('keine', 'keine'), ('Vorkenntnisse', 'Vorkenntnisse'), ('Gut', 'Gut'), ('Fliessend', 'Fliessend'), ('Muttersprache', 'Muttersprache')], default='', max_length=13, verbose_name='Französisch'),
        ),
        migrations.AddField(
            model_name='sprecherinnen',
            name='italienisch',
            field=models.CharField(blank=True, choices=[('keine', 'keine'), ('Vorkenntnisse', 'Vorkenntnisse'), ('Gut', 'Gut'), ('Fliessend', 'Fliessend'), ('Muttersprache', 'Muttersprache')], default='', max_length=13, verbose_name='Italienisch'),
        ),
        migrations.AddField(
            model_name='sprecherinnen',
            name='niederländisch',
            field=models.CharField(blank=True, choices=[('keine', 'keine'), ('Vorkenntnisse', 'Vorkenntnisse'), ('Gut', 'Gut'), ('Fliessend', 'Fliessend'), ('Muttersprache', 'Muttersprache')], default='', max_length=13, verbose_name='Niederländisch'),
        ),
        migrations.AddField(
            model_name='sprecherinnen',
            name='polnisch',
            field=models.CharField(blank=True, choices=[('keine', 'keine'), ('Vorkenntnisse', 'Vorkenntnisse'), ('Gut', 'Gut'), ('Fliessend', 'Fliessend'), ('Muttersprache', 'Muttersprache')], default='', max_length=13, verbose_name='Polnisch'),
        ),
        migrations.AddField(
            model_name='sprecherinnen',
            name='portugiesisch',
            field=models.CharField(blank=True, choices=[('keine', 'keine'), ('Vorkenntnisse', 'Vorkenntnisse'), ('Gut', 'Gut'), ('Fliessend', 'Fliessend'), ('Muttersprache', 'Muttersprache')], default='', max_length=13, verbose_name='Portugiesisch'),
        ),
    ]
