# Generated by Django 4.2 on 2023-04-11 22:05

from django.db import migrations, models
import multiselectfield.db.fields
import multiselectfield.validators


class Migration(migrations.Migration):

    dependencies = [
        ('angebote', '0011_sprecherinnen_englischus_sprecherinnen_französisch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprecherinnen',
            old_name='geburtsdatum',
            new_name='geburtsjahr',
        ),
        migrations.AddField(
            model_name='sprecherinnen',
            name='geschlecht',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('W', 'W'), ('D', 'D')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='sprecherinnen',
            name='mindesthonorar',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sprecherinnen',
            name='russisch',
            field=models.CharField(blank=True, choices=[('keine', 'keine'), ('Vorkenntnisse', 'Vorkenntnisse'), ('Gut', 'Gut'), ('Fliessend', 'Fliessend'), ('Muttersprache', 'Muttersprache')], default='', max_length=13, verbose_name='Russisch'),
        ),
        migrations.AddField(
            model_name='sprecherinnen',
            name='spanisch',
            field=models.CharField(blank=True, choices=[('keine', 'keine'), ('Vorkenntnisse', 'Vorkenntnisse'), ('Gut', 'Gut'), ('Fliessend', 'Fliessend'), ('Muttersprache', 'Muttersprache')], default='', max_length=13, verbose_name='Spanisch'),
        ),
        migrations.AddField(
            model_name='sprecherinnen',
            name='stimmalter',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Kind', 'Kind'), ('Teenager', 'Teenager'), ('junge Erwachsene', 'junge Erwachsene'), ('beste Jahre', 'beste Jahre'), ('Senior:in', 'Senior:in')], default=None, max_length=52, validators=[multiselectfield.validators.MaxValueMultiFieldValidator(5)]),
        ),
        migrations.AddField(
            model_name='sprecherinnen',
            name='türkisch',
            field=models.CharField(blank=True, choices=[('keine', 'keine'), ('Vorkenntnisse', 'Vorkenntnisse'), ('Gut', 'Gut'), ('Fliessend', 'Fliessend'), ('Muttersprache', 'Muttersprache')], default='', max_length=13, verbose_name='Türkisch'),
        ),
    ]
