# Generated by Django 4.2 on 2023-04-12 01:58

from django.db import migrations
import multiselectfield.db.fields
import multiselectfield.validators


class Migration(migrations.Migration):

    dependencies = [
        ('angebote', '0012_rename_geburtsdatum_sprecherinnen_geburtsjahr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprecherinnen',
            name='dialekte',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Bayerisch', 'Bayerisch'), ('Berlinerisch', 'Berlinerisch'), ('Fränkisch', 'Fränkisch'), ('Hessisch', 'Hessisch'), ('Norddeutsch', 'Norddeutsch'), ('Rheinisch', 'Rheinisch'), ('Sächsisch', 'Sächsisch'), ('Schwäbisch', 'Schwäbisch'), ('Badisch', 'Badisch'), ('Schweizerdeutsch', 'Schweizerdeutsch'), ('Westfälisch', 'Westfälisch'), ('Wienerisch', 'Wienerisch')], default=None, max_length=132, validators=[multiselectfield.validators.MaxValueMultiFieldValidator(12)]),
        ),
    ]
