# Generated by Django 4.2 on 2023-04-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angebote', '0013_sprecherinnen_dialekte'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprecherinnen',
            name='poC',
            field=models.CharField(blank=True, choices=[('Ja', 'Ja')], default='', max_length=2),
        ),
    ]
